name: Nightly CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nightly
  cancel-in-progress: true

jobs:
  cabal:
    name: Documentation generation
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        ghc: [
          9.12.4,
          9.10.3,
          9.8.4,
          9.6.7
        ]
    steps:
      - uses: actions/checkout@v6

      # Perhaps we should preinstall these on the container?
      # This step always takes a minute...
      # We'd lose the ability to select the version of cabal inside of the runner though
      - name: Install GHC
        id: ghc-install
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest

      - uses: tespkg/actions-cache/restore@e07e2d4953dc8c020d447363e5064e36d04f3cf9
        with:
          endpoint: "192.168.102.136"
          port: 9000
          insecure: true
          accessKey: "${{ secrets.S3_ACCESS_KEY }}"
          secretKey: "${{ secrets.S3_SECRET_KEY }}"
          bucket: runner
          region: local
          use-fallback: false
          retry: false
          key: ${{ runner.os }}-${ matrix.ghc }-cabal-${ hashFiles( ${{ steps.ghc-install.outputs.cabal-store }}, "~/.cache/cabal" ) }
          restore-keys: ${{ runner.os }}-${ matrix.ghc }-cabal-
          path: ${{ steps.ghc-install.outputs.cabal-store }}

      - name: Version information
        run:
          cabal --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libtinfo-dev tree iverilog -y

      - name: Build documentation
        run: .github/scripts/build_docs.sh

      # - uses: tespkg/actions-cache/save@e07e2d4953dc8c020d447363e5064e36d04f3cf9
      #   with:
      #     endpoint: "192.168.102.136"
      #     port: 9000
      #     insecure: true
      #     accessKey: "${{ secrets.S3_ACCESS_KEY }}"
      #     secretKey: "${{ secrets.S3_SECRET_KEY }}"
      #     bucket: runner
      #     region: local
      #     use-fallback: false
      #     retry: false
      #     key: ${{ runner.os }}-${ matrix.ghc }-cabal-${ hashFiles( ${{ steps.ghc-install.outputs.cabal-store }}, "~/.cache/cabal" ) }
      #     path: ${{ steps.ghc-install.outputs.cabal-store }}

