name: Nightly

on:
  push:
    branches:
      - '*'

jobs:
  nightly:
    name: Engineer Gaming
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: [
          "9.10.3",
          # "9.8.2",
          # "9.6.4"
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # TODO:
        # https://github.com/marketplace/actions/s3-cache

      # - name: Install GHC
      #   uses: haskell-actions/setup@v2
      #   with:
      #     ghc-version: ${{ matrix.ghc }}
      #     cabal-version: "3.12.1.0"

      - name: Make cache dir
        run: mkdir ~/non-nix-cache

      - uses: tespkg/actions-cache@v1
        with:
          endpoint: 192.168.102.136:9000
          insecure: true
          accessKey: "${{ secrets.S3_ACCESS_KEY }}"
          secretKey: "${{ secrets.S3_SECRET_KEY }}"
          bucket: runner
          use-fallback: false
          retry: true
          key: test
          path: ~/non-nix-cache

      - name: List
        run: ls ~/non-nix-cache

      - name: Write
        run: echo "Engineer Gaming" > ~/non-nix-cache/gaming

      # - name: Setup
      #   run: .github/scripts/cabal_setup.sh
      #
      # - name: Build
      #   run: .github/scripts/cabal_build.sh
      #
      # - name: Test setup
      #   run: .github/scripts/cabal_setup_nocache.sh
      #
      # - name: Test
      #   run: echo ":)"
