name: Nix Packaging

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Make each build a seperate step
  # We also want to cache every succesfull build, even if other subprojects fail

  packages_common:
    name: Build Common (${{matrix.ghc}})
    runs-on: self-hosted
    strategy:
      # If caching fails for one package, then we are still interested in caching other packages
      fail-fast: false
      matrix:
        ghc: [
          "ghc9101",
          "ghc982",
          "ghc964"
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate cache
        env:
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
        run: bash .github/scripts/attic-auth.sh

      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-prelude
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-lib
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-ghc

  packages_tests:
    name: Unit & Doc Tests (${{matrix.ghc}})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        ghc: [
          "ghc9101",
          "ghc982",
          "ghc964"
        ]
    needs: packages_common
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate cache
        env:
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
        run: bash .github/scripts/attic-auth.sh

      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-lib-hedgehog
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-prelude-hedgehog
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-cosim

  packages_other:
    name: Build Others (${{matrix.ghc}})
    runs-on: self-hosted
    strategy:
      matrix:
        ghc: [
          "ghc9101",
          "ghc982",
          "ghc964"
        ]
    needs: packages_common
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate cache
        env:
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
        run: bash .github/scripts/attic-auth.sh

      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-term
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-benchmark
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-profiling-prepare
      - run: .github/scripts/nix-build.sh .#clashPackages-${{matrix.ghc}}.clash-profiling

  developer_shells:
    name: Build Developer Shells (${{matrix.ghc}})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        ghc: [
          ghc9101,
          ghc982,
          ghc964
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate cache
        env:
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
        run: .github/scripts/attic-auth.sh

      - name: Nix devShell ${{matrix.ghc}}
        run: .github/scripts/nix-build.sh .#devShells.x86_64-linux.${{matrix.ghc}}

  ffi-tests:
    name: Run FFI tests (${{matrix.ghc}})
    runs-on: self-hosted
    strategy:
      matrix:
        ghc: [
          ghc9101,
          ghc982,
          ghc964
        ]
      fail-fast: false
    needs: packages_common
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate cache
        env:
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
        run: bash .github/scripts/attic-auth.sh

      - name: Build FFI tests
        run: nix build -L .#clash-ffi --out-link compiled

      - name: Run FFI tests
        run: ./compiled/bin/ffi-interface-tests

  # testsuite:
  #   name: Run Testsuite (${{matrix.ghc}}, ${{matrix.testsuite}})
  #   runs-on: self-hosted
  #   strategy:
  #     matrix:
  #       testsuite: [
  #         testsuite-vhdl,
  #         testsuite-verilog,
  #         testsuite-systemverilog
  #       ]
  #       ghc: [
  #         ghc9101,
  #         ghc982,
  #         ghc964
  #       ]
  #     fail-fast: false
  #   needs: packages_tests
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Authenticate cache
  #       env:
  #         ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_SECRET }}
  #       run: bash .github/scripts/attic-auth.sh
  #
  #     - name: Build CI shell
  #       run: |
  #         nix develop .#devShells.x86_64-linux.ci.testsuite-${{matrix.ghc}} --profile /tmp/ci
  #         attic push public $(nix path-info /tmp/ci)
  #
  #     - name: Testsuite (${{matrix.testsuite}})
  #       run: nix develop /tmp/ci -c bash -- .github/scripts/run-unittests.sh ${{matrix.testsuite}}
